options:
  logging: CLOUD_LOGGING_ONLY
  logStreamingOption: STREAM_ON

substitutions:
  _PORT: "3000"
  _SERVICE: "none"

steps:
  # Detect and store service name
  - name: "gcr.io/cloud-builders/gcloud"
    id: "detect-service"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "_COMMIT_MESSAGE is: '${_COMMIT_MESSAGE}'"

        if echo "${_COMMIT_MESSAGE}" | grep -q "\[desplegar orquestador\]"; then
          echo "orquestador" > _SERVICE.txt
        elif echo "${_COMMIT_MESSAGE}" | grep -q "\[desplegar pedidos\]"; then
          echo "pedidos" > _SERVICE.txt
        elif echo "${_COMMIT_MESSAGE}" | grep -q "\[desplegar productos\]"; then
          echo "productos" > _SERVICE.txt
        elif echo "${_COMMIT_MESSAGE}" | grep -q "\[desplegar rutas\]"; then
          echo "rutas" > _SERVICE.txt
        elif echo "${_COMMIT_MESSAGE}" | grep -q "\[desplegar todos\]"; then
          echo "todos" > _SERVICE.txt
        else
          echo "No service specified in commit message"
          exit 1
        fi

        echo "âœ… Detected service: $(cat _SERVICE.txt)"

  # Build and push Docker image
  - name: "gcr.io/cloud-builders/docker"
    id: "build-and-push"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        SERVICE=$(cat _SERVICE.txt)
        echo "âœ… Detected service: $SERVICE"

        SERVICES=("orquestador" "pedidos" "productos" "rutas")

        for svc in "${SERVICES[@]}"; do
          if [ "$SERVICE" = "$svc" ] || [ "$SERVICE" = "todos" ]; then
            echo "ðŸš€ Building and pushing $svc"
            docker build -t gcr.io/$PROJECT_ID/$svc:$COMMIT_SHA ./$svc
            docker tag gcr.io/$PROJECT_ID/$svc:$COMMIT_SHA \
              us-central1-docker.pkg.dev/$PROJECT_ID/proyecto-final/$svc:$COMMIT_SHA
            docker push us-central1-docker.pkg.dev/$PROJECT_ID/proyecto-final/$svc:$COMMIT_SHA
          fi
        done

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        SERVICE=$(cat _SERVICE.txt)
        echo "âœ… Detected service: $SERVICE"

        SERVICES=("orquestador" "pedidos" "productos" "rutas")

        for svc in "${SERVICES[@]}"; do
          if [ "$SERVICE" = "$svc" ] || [ "$SERVICE" = "todos" ]; then
            echo "âš™ï¸ Deploying $svc to Cloud Run"

            if [ "$svc" = "orquestador" ]; then
              echo "URL_PEDIDOS=${_URL_PEDIDOS}" > ./$svc/.env.production
              echo "URL_PRODUCTOS=${_URL_PRODUCTOS}" >> ./$svc/.env.production
              echo "URL_RUTAS=${_URL_RUTAS}" >> ./$svc/.env.production
              echo "URL_DEEPSEEK=${_URL_DEEPSEEK}" >> ./$svc/.env.production
              echo "DEEPSEEK_MODEL=${_DEEPSEEK_MODEL}" >> ./$svc/.env.production
              echo "DEEPSEEK_API_KEY=$(gcloud secrets versions access latest --secret=deepseek_api_key --format='get(payload.data)' --project=$PROJECT_ID | base64 --decode)" >> ./$svc/.env.production
            else
              echo "DB_HOST=/cloudsql/$PROJECT_ID:us-central1:$svc" > ./$svc/.env.production
              echo "DB_USER=${_DB_USER}" >> ./$svc/.env.production
              echo "DB_PORT=${_DB_PORT}" >> ./$svc/.env.production
              echo "DB_NAME=${_DB_NAME}" >> ./$svc/.env.production
              echo "DB_PASSWORD=${_DB_PASSWORD}" >> ./$svc/.env.production
            fi

            gcloud run deploy $svc \
              --image us-central1-docker.pkg.dev/$PROJECT_ID/proyecto-final/$svc:$COMMIT_SHA \
              --region us-central1 \
              --platform managed \
              --port 3000 \
              --memory 512Mi \
              --cpu 1 \
              --min-instances 0 \
              --max-instances 1 \
              --allow-unauthenticated
          fi
        done

timeout: "1800s"
